version: "3.8"

services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    ports:
      - "25565:25565"
      - "25575:25575" # RCON si lo usás
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      MEMORY: "8G"
      FORGE_INSTALLER: "forge-1.20.1-47.3.22-installer.jar"
      LEVEL_TYPE: "lostcities"
    volumes:
      - /home/administrator/servers/server_mods/Minecraft:/data
    restart: unless-stopped
